{{- if .Values.mongodb }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-personal-data-import.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- with .Values.mongodb.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName | default "fintech-personal-data-import" }}
        {{- include "fintech-personal-data-import.selectorLabels" . | nindent 8 }}
      name: mongodb-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
