{{- if .Values.rabbitmq }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-personal-data-import.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- with .Values.rabbitmq.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName | default "fintech-personal-data-import" }}
        {{- include "fintech-personal-data-import.selectorLabels" . | nindent 8 }}
      name: rabbitmq-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
