# SealedSecrets para MongoDB - Entorno de Desarrollo
# ------------------------------------------------
# Este archivo contiene los secretos sellados para MongoDB que
# deben ser utilizados durante el despliegue con Helm.

# Estructura para los datos encriptados del SealedSecret
mongodb:
  encryptedData:
    # Cadena de conexión URI para MongoDB
    # Formato encriptado: AgXXXXXX...
    uri: AgATiJJ8s9VlcZazvtbWYgQkLmrdoCO8nauwSqEb3sgeFEECaiZ5HnR9Sk7OT0404DMDwzhbuKfW0Xd+lZ0DPNIwRn+769BE5/pepgOFstu4LZAOjq+qKw563BRUjqCRiMrvqV5RfuZH4CWIItJoPK9fGl9KaP5D7wjalPC4CKcbkUkbKi/2CllCCv1AmyUXv5fEHlBVfIPodQFXTRW4KGd4r993XkbMtOKlEO/DqpECLFS0tI8hGNrp5Pd5rkjwZa8jV4is0kY4JagIs7/gm5Cdrz1Np1r9RuO6haMrK/s01igkUtV/L4x4U6qhqoKVzXUiwpncnUei9d6NrUYxeM7Wwye0mgptFp6lh+sUCNgp/YGVXqZg2a9bPOMX/vDLAMB7GHFlseLYUnhkBLUpwsXPXhCwcacC1sKxvlfFShsCjLDwrgjR0nrM6HDOPacTwsR+0zNqEBT2fGvOKF5sjeqkw/iOpDy35EgsmwqZ3/3C/fdMeJgyTmAtPveOB+35Fyc0K1naFjItcMBeqQR4l0n7Mnx2zWCVl0HbjN13mXLegqg0p2hLlvaoO3V4SnmByFy8gwTnYx5Y/K54x1ibmnpM0/sV2lj5RIRL4WKRaSXj/KMJ2Qn9EeicjEhVzH9s6qbFWKzxB7J4hbqJ2kPOLDlKsyGulBcq1sunNl0F72/UCv3EGgaASYG9PImHgr4CBd1dhnRJPKmA91vNmfk4xQGtqOMxC3TlGbWPdf7zHdfOyzCLTzZ3wyKEu+hs7Wn1Ura2SY9LuPJaJzyQsj+/764vyGjfyRGXtjZsBHjSGzkQofbfV8pwOi0UsqQLNK4hssbTcnoltGQi0daf4kgiyOurWP5d96w=