---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: fintech-dev
spec:
  encryptedData:
    url: AgAZFsOdgTEkcn0+bOytC4jxbLAcEAX+UNJnuqZtPmwVeYL/RZd0gZ0aatzolCF21TBv6Cty8CTZ4alUQJgkvjkOil6bxJWE4h7fjvDA09TjPIwYelNKZcKYi0OJ/qa4PiJlIGevvjRI/z9SGyGsabFFUUOD71JHc5Aun9es8k5bjbuZLzpDK/l6v0XzYDmGATG8dGNUKY/CPMDmQt+TPco4XPNb/2jUuNUVjsUK5I0hvPuj1TO++imYmpohFwHNTEL1E+PEVaKmWtnMTy+byd6LKqWVwpa5SaIOxzisP6R5BPvkeZBwQToIj/CxYZ1KWWKz6QBGIam1qlbCUv4GYKw0aqXT9mHpEry6KH0vCczRLSAeE6xw+YxINHJOCwg6i/5MSX0V4LKoSp3qMFjmVjlIpEDyYd0OKf6or3a71gad7mJxVbDUIcrxvpKlF1nkpGqCnrlAGPnDPVGLjyeGKJVI7+bzVbWeMFON9e07bCAi+My7hEwME00rR/XLBmCX07cwd5/wLKWqHB+dnu/SaTZWSvF8ji+36ldrsaRgLZAKmRUxyW26lZDA+PL9EMV7aqMzxGJqcZ+Q2mTvRZsmqUwxSyjbcm6Usd/GQmW3YQSOMBnX1+vtr+efHIL70bu+JlZEb/wFk6rWQ7jzHeCsqtRpIJwh/StSmQ7NcL3lSAkyhKxaxe4OUP32r6jft092IQdPPjAeXqYrnPg+1G0tO5qvrEUutimXNGhywXP1/G2mTHouoy8UHmbYsD23wrdVRe1XPhdEAU+lTD8usSO8oDA3svwpHwfy8vWDDm/2r5wbceQzKWgpypc9qtFw+4ZvRkjXO7wxOJj2I4nnLAElMO4=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fintech-data-import
        environment: dev
      name: rabbitmq-credentials
      namespace: fintech-dev
    type: Opaque
