---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: fintech-dev
spec:
  encryptedData:
    url: AgCBpc7KrDSoNfPe8epOWIc/O31m31GKI+fqrsF8iKWDOZxPAMSTOmTVSL73z8CSONeRgPaIiNNWl/HnffXgTCR4GrJfkjOXB/ajt4OpsdCjPS0bLwDEEshfia14NI9wNK7x6YWRPry7UagVqp9x+enk3oj/lloPCVJy2NI7Kdtor0lad/OBWu6xJAWakqhtg5w42adgQ50UapEjsnE0tYCfOebj/l+WZu23V9A1UkscJy+66tMh3e5dI/TOBiwL+kTqflVKneM484HMBFYdMsToCdnKrJEvb0gsq8d0xFdqZJh19Wd8hRO7W7xs5If2twIPAUUbE7RugGI7NOJqVTjxojHv0/2uDmIAGm9gklvwCQbwU+HoCzdunXH1ARdSip7WBQNDKHW+LbZV/mlghNZntSftUeNDemwuX4rt8jzZyNP8eN8F1/GIez0vRTWkypa3JVA0/rCcJTPM7quPc+OtFE9SknbzuFuH/fsZptatyu3CwplQ1yiIz/1EewNYeFjbGOlikjbd9Nl1dw26pZBbehIhqOhkoeZwuv7F10dlS9ip6UA/tiBxW4bVQjJbWcj6cnvKqpBRIetyWuF+JmC7/2kehY4VXz1NLFJWf5yFPDD4MEYfJXeap0VRmhrwnSTbSi9xEY6qQH8jL1TtRClM2p5I0hKg5gD2nREl5Y3WqJoQgUu1vd+XzzDvMI3AUDx27ndB8f/l+yYmf8xBsz5E03U9V/COEUTulj5SPz61f1FqHA2QIAjY
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fintech-data-import
        environment: dev
      name: rabbitmq-credentials
      namespace: fintech-dev
    type: Opaque
