# SealedSecrets para RabbitMQ - Entorno de Desarrollo
# ------------------------------------------------
# Este archivo contiene los secretos sellados para RabbitMQ que
# deben ser utilizados durante el despliegue con Helm.

# Estructura para los datos encriptados del SealedSecret
rabbitmq:
  encryptedData:
    # URL de conexión para RabbitMQ
    # Formato encriptado: AgXXXXXX...
    url: AgBcpWQQShKD5UGun3mWxGQnZ0KngWE2rtnLffRjU9A/OoWBAhPwMpCvWtxjDWUXWFS9uWBoQUMWYZEUYYUIB4Nr4dt+1T/eYw1aDqeU2TiUpH6/C7pBJdmeEjjBGJAcHr0Mzr2U06B79sj/r+aKaq0B42yEtUDrM4Gb8f+u1r/23YfIKHq5gRaq58ozSkcDIXzrafym1LjD8h8t8PXK1E8eeXeDF1R3rrYH7vSTNcnj+Fff6kXygvow0nibAtTe3qPV2l/AhhkxfDzMSCmukiqyzAO55g7SML3sspwphqwnYFse/h9qXc7vICjvyOWiUFZd0SjFPr3lxz629R2fdofhyWkVB2SY/Brss50pyD8GVMty8PlIQzs9s3Xcz4k8Y66IPsCFITsY3lGFkfaT/vfNCpGNWnWTyRcifV2UvSFqks1zU2mO/DsCWh2YLDA8w1WR+TY6NTV77XN07QokSO4i6votnwNFIPbPYwomrJJrLZPpUQ+IrfOZviyEy3TvILN/10nl0NiM/abeMwmLNsaGq19qIM4jF6CC0CbK/ZTemrnrgnstCXyPmYendA1PdYc4qyKShe+CYQWZke2gIZcYBe9ffjKgnU8E94JQJ6ESAiuO2LsVUhaFxTStA2/wUsR1gbwPZZzd4KXcb9LqZQ7emtKRclWgeqHHtFpiX5WSsncf6WuCxgkx4AxkdHzXKFSpTXCiWrnrhwYnUdHjKkNb0DlxnebVlQLWUaJPj/k8EI2m3gISvbT6