replicaCount: 1

image:
  repository: ${CONTAINER_REGISTRY}/fintech-personal-data-import
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "fintech-personal-data-import"

serviceAccount:
  create: true
  annotations: {}
  name: "fintech-personal-data-import-sa"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: data-import.fintech.local
      paths: 
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3001"
  - name: LOG_LEVEL
    value: "info"
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-credentials
        key: uri
  - name: MONGODB_DB_NAME
    value: "fintech"
  - name: RABBITMQ_URL
    valueFrom:
      secretKeyRef:
        name: rabbitmq-credentials
        key: url
  - name: RABBITMQ_EXCHANGE
    value: "fintech-events"
  - name: RABBITMQ_EXCHANGE_TYPE
    value: "topic"
  - name: RABBITMQ_QUEUE
    value: "file-import-queue"
  - name: RABBITMQ_ROUTING_KEY
    value: "file.uploaded"
  - name: RABBITMQ_STATUS_ROUTING_KEY
    value: "file.import.status"
  - name: MAX_CONCURRENT_PROCESSING
    value: "3"
  - name: DELETE_AFTER_PROCESSING
    value: "true"
