apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fintech-data-import-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/open-liontechsolution/fintech-personal-data-import.git
    targetRevision: develop
    path: helm
    helm:
      valueFiles:
        - environments/dev/values-dev.yaml
        - environments/dev/mongodb-sealedsecrets-values.yaml
        - environments/dev/rabbitmq-sealedsecrets-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fintech-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
